server:
  port: 7070

spring:
  rabbitmq:
    first:
      host: 39.108.13.2
      port: 5672
      username: xbm
      password: xbmchina
      virtual-host: /
    second:
      host: 192.168.56.16
      port: 5672
      username: guest
      password: guest
      virtual-host: /



